tayjiahui/ABC_FYP_ST0508

- frontend/next.config.js
> Removed Next.config.js

- package-lock.json
- package.json
- Installed Moment.js packages into frontend for datatime format changes
> Moment.js Package Installation

- components/navbar.js
- pages/Login.js
- pages/PurchaseRequest/CreatePR.js
- pages/PurchaseRequest/[prID].js
- pages/PurchaseRequest/index.js
- pages/index.js
- Changed timestamp format for Target Delivery Date in view by PR ID page
- Mass changed class attributes to className attributes
- Adding alt attributes to Image
> Amalie01 - #9 & Minor Code edits

- pages/PurchaseRequest/index.js
- search box on purchase request page can now be used to search for PR
> #9 -Added functional Search box for purchaser view

- pages/PurchaseOrder/index.js
Main Payment Tracking CSS to bootstrap.
> Bootstrap Edits #39, Main Payment Tracking Bootstrap edits

- components/navbar.js
- pages/PurchaseRequest/[prID].js
- pages/PurchaseRequest/index.js
- public/rightArrowWhite.svg
- styles/global.css
- styles/viewPR.module.css
#9 - Purchase Request
- Added PR No. column in view all pr page, onclick has the same functions as eye icon (Onclick expands to shows Product Lines)
- Changed timestamp formats to "D Month YYYY"
- Changed "Deny" to "Reject" for approver's section
- Changed Appr Comments under the rejected PR section to a editable input box for reappeal
> Amalie01 - #9

- package-lock.json
- pages/Login.js
- pages/Profile.js
- pages/PurchaseRequest/CreatePR.js
- pages/PurchaseRequest/[prID].js
- pages/PurchaseRequest/index.js
- pages/_app.js
- pages/api/auth/[...nextauth].js
**#9 Purchase Request**
- Added apprUserID to approver update PR API body
- Custom Attribute fix from "data-unitPrice" to "data-unitprice"
- Added purchaseTypeID to create PR API body
**#38 User Login Integration**
- Added signIn & signOut events for integration [WIP]
- next-auth signIn event now can successfully pass through authentications until check email API
**#58 Ad-Hoc Flow**
- Functional Create Ad-Hoc Purchase Form
- Added view all Ad-Hoc Purchases (Approver's View) [WIP]
- Added view Ad-Hoc Purchases by UserID (Purchaser's View) [WIP]
> Amalie01 - #9 , #38 & #58

- package-lock.json
- pages/TrackOrder/[poID].js
- pages/TrackOrder/index.js
- Fixed qty received issues
- Changed poID of view PO by id page to all prID disguised as poID
> Amalie01 - #75

- pages/PurchaseRequest/[prID].js
- pages/test.jsx
- styles/viewPR.module.css
#81 - Convert PR to PO
- Added Functional Convert to PO button (now downloads generated PDF & creates PO in DB)
- Added view PO  PDF button for approved & converted PRs (Dynamic Rendering)
- Added download PO PDF button for approved & converted PRs (Dynamic Rendering)
> Amalie01 - #81

- components/alert.js
- components/barchart.js
- components/poAmt.js
- components/prAmt.js
- pages/Home.js
- pages/Profile.js
- pages/PurchaseRequest/CreatePR.js
- pages/PurchaseRequest/[prID].js
- pages/PurchaseRequest/index.js
- pages/TrackOrder/[poID].js
- pages/test.jsx
- styles/createPR.module.css
- styles/purchaseReq.module.css
**#9 - Purchase Request (Purchaser)**
- Added Functional Reappeal for rejected PRs
- Added dynamic search bar
- Added search filters
**#38 - User Login**
- Added User Details to Profile page
**#50 - Purchase Request (Approver)**
- Added dynamic search bar
- Added search filters
**#58 - Ad-Hoc Flow**
- Added dynamic search bar for ad-hoc
- Added search filters for ad-hoc
- Edits to Ad-hoc toggle
**#84 - Homepage**
- Added functional quick action create ad-hoc button
**General**
- Alert testing codes
> Amalie01- #9, #38, #50 & #58

- pages/PurchaseRequest/index.js
- pages/index.js
#39 - Bootstrap Edits
- Edited bootstrap for view adhoc purchases
> Amalie01 - #39

- pages/PurchaseOrder/index.js
- styles/viewPO.module.css
Bootstrap fixes : 
Box Shadow on hover
> Payment Tracking #26, Bootstrap edit for main Payment Tracking Page

- pages/PurchaseRequest/CreatePR.js
- pages/PurchaseRequest/[prID].js
- pages/PurchaseRequest/index.js
- pages/TrackOrder/[poID].js
- pages/TrackOrder/index.js
- styles/trackOrder.module.css
**#9 - Purchase Request**
- Changed View All option to toggle
- View all Toggle Changes back to view by id when unchecked
**#58 - Adhoc Flow**
- After adhoc is created, "PO" created for adhoc also
- Added adhoc view by id file
**#75 - Purchase Order**
- Added Ad Hoc Toggle to track Order Page
- Functional View Adhoc toggle
- Fixed PO by PO ID page
**#81 - Convert PR to PO**
- After Converting PR to PO, page redirects to PO page by PR ID
> Amalie01 - #9, #58, #75, #81

- components/Popup.js
- pages/TrackOrder/[poID].js
- styles/calendar.module.css
- get userid from local storage 
- remove add invoice and do button from poID
> get userid from localstorage and remove add DO

- pages/PurchaseRequest/CreatePR.js
- pages/PurchaseRequest/index.js
- pages/TrackOrder/[poID].js
- pages/TrackOrder/index.js
- pages/fakeLogin.js
#123 - Audit Logs
- Added create audit log api for edit item quantity(partial delivery)
- Added create audit log api for update Purchase Order Status to view PO by id page
- Added create audit log api for update PUrchase Order Status to main track order page
> Amalie01 - #123

- pages/PurchaseOrder/[poID].js
- Added audit logging to update payment status on track payment view by id page
> #123 -Added audot logging to update payment status

- pages/PurchaseOrder/[poID].js
- pages/TrackOrder/AdHoc/[poID].js
- pages/TrackOrder/[poID].js
- Uploading of PDF for Invoice (Track Order)
- Uploading of PDF for Delivery Order (Track Order)
- Uploading of PDF for Ad-Hoc purchases 
- Fetching of PDF for Ad-Hoc purchases
- Edits of bootstrap code
> #124, Upload & Fetch PDF for Track Order & Ad-hoc

- components/alert.js
- components/navbar.js
- pages/AlertExample.jsx
- pages/PurchaseRequest/index.js
- pages/TrackOrder/[poID].js
- pages/TrackOrder/index.js
- pages/api/auth/[...nextauth].js
- pages/test.jsx
- styles/purchaseReq.module.css
#9 - Purchase Request
- Convert to Purchasers view PR to combined adhoc & PR view
- Scrollable rows only
#38 - User Login
- Added JWT to company SSO login route
#129 - Components
- Changed alert component position to top right corner
#135 - Transaction Report
- Downloadable excel & csv testing
> Amalie01 - #9, #38, #129, #135

- pages/PurchaseOrder/[poID].js
- PDF changed to view on new tab
- Users click on View Receipt button to make pdf appear on a new tab
> #124, PDF is now changed to display in a new tab

- pages/PurchaseRequest/CreatePR.js
- pages/Supplier/[supplierID].js
- Added MOQ to PR creaiton, if the existing supplier has MOQ, it will check against the total price of all line items. If total price does not meet the requirements of MOQ, the creation of PR is not allowed. Else if the total price meets, or if supplier has no existing MOQ, the PR can be created. 
- Added MOQ & deliveryTimeLine fields to creating and updating supplier.
> #9, #68, Added MOQ to PR creation & Added MOQ & deliveryTimeLine fields to supplier

- pages/Admin/Home.js
- pages/Admin/Transactions/index.js
- pages/PurchaseRequest/[prID].js
- pages/TrackOrder/[poID].js
Added alerts to following
-  PO PDF download
- Transaction report downloads
- Edit qty for partial delivery
- Update purchase status on PO page
> Amalie01 - #75, #135, #139

- pages/TrackOrder/AdHoc/[poID].js
- Added new way of PDF display, New tab
- Added Alert box for upload of receipt
> #124, Updated version of PDF & Upload Alert

- pages/TrackOrder/AdHoc/[poID].js
> Minor edits of states

- components/navbar.js
- pages/Admin/AuditLogs/index.js
- pages/Admin/Configurations/index.js
- pages/Admin/Home.js
- pages/Admin/Transactions/index.js
- pages/Admin/Users/index.js
- pages/Transactions/index.js
- styles/adminConfiguration.module.css
- styles/auditLog.module.css
#135 - Transaction Report
- Added Transactions Tab for Approvers & Finance Staff
#139 - Admin Page
- Removed GST button from transactions page
- Configurations base page
> Amalie01 - #135, #139

- pages/PurchaseOrder/[poID].js
- pages/TrackOrder/[poID].js
- Addition of Delivery date to PO's if any for track order
- Addition of Delivery date to PO's if any for track payment
- if delivery date value is null, the section will not be displayed
> #152, Addition of delivery date to PO's.

- pages/PurchaseRequest/[prID].js
- delivery date calculation based on when the PR is converted to PO
> #152, Delivery Date Calculation for PO's

- components/adminNavBar.js
- pages/Admin/AuditTrail/index.js
- pages/Admin/Home.js
- pages/Admin/Users/index.js
- pages/PurchaseRequest/index.js
- pages/TrackOrder/[poID].js
#139 -Audit Trail
- Change Audit Logs to Audit Trail
General Changes
- Minor wording chnages
> Amalie01 - #139

- pages/Admin/Configurations/index.js
- Purchase Status deletion for admins 
- Payment Status deletion for admins
> #139, Delete Purchase & Payment status

- pages/Admin/Configurations/index.js
- Delete Purchase Status
- Delete Payment Status 
- Alerts for both
- Confirmation for both
> Admin Status Deletion

- pages/PurchaseOrder/[poID].js
- If not finance staff, cannot perform actions 
- Alert boxes for changes 
- Added deletion of receipt 
- Added such that if there is existing receipt, cannot upload a new receipt
> #26, #129, #124, Added Restrictions, Alert Boxes, Delete Receipt

- pages/Admin/Configurations/index.js
- Delete payment status alert component 
- Delete purchase status alert component
> Admin delete status alert component

- pages/TrackOrder/[poID].js
- Added view Invoice
- Added view DO
- Added delete invoice
- Added delete DO 
- Added delete invoice alert
- Added delete DO alert
> #124, added view & delete invoice/do with alerts
